joy_teleop:
  ros__parameters:
    move:
      type: topic
      interface_type: geometry_msgs/msg/TwistStamped
      topic_name: bumperbot_controller/cmd_vel
      deadman_buttons: [9]
      axis_mappings:
        twist-linear-x:
          axis: 1  # Left stick up/down
          scale: 1.0
          offset: 0.0
        twist-angular-z:
          axis: 2  # Left stick left/right for turning
          scale: 2.0
          offset: 0.0